### PR TITLE
update juju 1.25 metadata docs

### PR DESCRIPTION
**Pull request by Cynerva**
Add docs for `storage`, `payload`, `series`.

Related to #1100 which is for Juju2 docs - I pulled these definitions straight out of there.

Issue: #1079

### CODE REVIEW

**Comment by pmatulis** [comment]
If this is the same addition as in #1100 then we should request a backport in the associated bug (#1079).

**Comment by pmatulis** [comment]
@Cynerva You pulled those things from 2.0. Are we sure those items apply to 1.25?

**Comment by Cynerva** [comment]
@pmatulis Looks correct to me based on the schema here, which I believe is 1.25: https://github.com/juju/charm/blob/v5/meta.go#L669

**Comment by chuckbutler** [comment]
Yep, storage, payload, and series are all valid for 1.25.  Do note, that not all providers support storage, so its tricky to validate. At time of writing, I believe only OpenStack, and Amazon currently have storage support in 1.25.

**Pull request merged**
