### PR TITLE
New build tool

### PR DESCRIPTION
**Pull request by evilnick**
modified from generic tool used for other md docs, fixes issue of long files
also changes templates to avoid probs with jujucharms
changes location of output to facilitate language directories
rewrites image links to reference common media dir
added target 'new' to makefile

DO NOT MERGE, still WIP

### CODE REVIEW

**Comment by evilnick** [comment]
@fabricematrat would you mind checking this over also - it adds a new build tool to get over the filelength issue. I have changed the templates also. i just want to check it isn't going to break your side of things when we merge it

**Comment by mitechie** [comment]
Thanks @evilnick I've asked @kadams54 to investigate and make sure we're solid on our end.

**Comment by kadams54** [comment]
@evilnick I'll continue keeping an eye on this but right now I'm not seeing anything that would cause a problem.

**Comment by petermatulis** [comment]
Dunno, maybe I'm doing something wrong but when I do 'make build' I still get these errors:

tools/build-from-source: line 7: /usr/bin/basename: Argument list too long
tools/build-from-source: line 7: /usr/bin/cheetah: Argument list too long

**Comment by evilnick** [comment]
@petermatulis yes, I left the old target for now, you need to ' make new' for the moment

**Comment by evilnick** [comment]
@petermatulis also, run make sysdeps first!

**Comment by evilnick** [comment]
@petermatulis okay, this should now work for you

Run 'make sysdeps' to make sure you have all the bits
then run 'make build'
and 'make serve' or whatever you usually do to test

I included a test page which has common elements on it (called test.md)
this also removes some of the old tools. I have left the multi-version builder, as this can be made to work with the new tool quite easily

**Comment by petermatulis** [comment]
Works. :+1:

**Comment by evilnick** [comment]
cool, i will merge it in the morning when I am a bit more alert, just on the off chance it disturbs the live docs

**Pull request merged**
