### PR TITLE
added clarification for firewall

### PR DESCRIPTION
**Pull request by pmatulis**
See PR #2021 for this change in 2.2.

### CODE REVIEW

**Comment by evilnick** [comment]
Ok, I will approve this, but this is exactly the wrong way around to do things!

**Comment by pmatulis** [comment]
I don't mind changing it. What is a better way?

**Comment by evilnick** [comment]
there isn't now. The better way would have been to do the original fix here, in this PR, and backport it to 2.2

It's not a major thing, but if we change this text again there is likely to be a conflict between master and 2.2 now

**Comment by pmatulis** [comment]
Oh that's what you mean. Yeah, I started out the 'status output' PR thinking I could go to master and backport everything but then I saw that the output for 2.3 and 2.2 differ. Then all hell broke loose.

**Pull request merged**
