### PR TITLE
Add documentation on metrics.

### PR DESCRIPTION
**Pull request by cmars**

### CODE REVIEW

**Comment by cmars** [comment]
@evilnick @urosj PTAL, thanks!

**Comment by evilnick** [comment]
I am out until Tuesday but I am sure @matthelmke will give it a once over.
Looks good from a casual read. Thanks for this!

**Comment by matthewhelmke** [comment]
@cmars These look good, thank you!

**Comment by cmars** [comment]
@evilnick @matthewhelmke Can we backport this into the Juju 2.0 docs? I see it under devel.

**Comment by matthewhelmke** [comment]
@cmars working on timing, but yes, we will get it in there asap.

**Pull request merged**
