### PR TITLE
updated info on getting and setting model config values

### LINKED ISSUE #1351: model command changes should be documented
`juju model-defaults` command(s) have been collapsed to one command.
`juju model-config` command(s) have been collapsed to one command.
`juju list-models` displays machine count and core count.

The syntax used to get and set model configuration values has changed.

#### Examples

Retrieve the full set of configuration for "application" and display it in YAML form.

`juju config --format=yaml application`

```
    key: foo
    Key2: bar
```

Set the configuration for key to value and key2 to value2.

`juju config application key=value key2=value2`

Retrieve just the value for a single key.
```
    juju config application key

    value
```

Reset the value of key and key2 to the default value as defined by the charm.

`juju config application --reset key,key2`

Configuration can also take a model identifier to allow you to set/retrieve the value from a model that is not your current default, and you can set and reset values on the same request, but you cannot retrieve a value and set or reset a value at the same time.
 
`juju config -m controller:model application key=foo --reset key2`

The behaviour of `juju model-config --reset` has changed. Previously, any reset attribute would revert to the empty value. Now, the value will revert to the closest inherited value.

Retrieve the full set of configuration defaults and display it in YAML form.

`juju model-defaults --format=yaml`

```
agent-metadata-url:
  default: ""
agent-stream:
  default: released
apt-ftp-proxy:
  default: ""
 ...
```

Set the default configuration value for all models in the controller for key to value and key2 to value2.

`juju model-defaults key=value key2=value2`

Retrieve just the value for a single key.

`juju model-defaults key`

Reset the value of key and key2 to the next closest default value.

`juju model-defaults --reset key,key2`

### PR DESCRIPTION
**Pull request by matthewhelmke**
Fixes #1351 
During review, please help me figure out whether the table on the page needs updating. This is the current output in 2.0rc1, but I do not know whether this list is exhaustive. These entries on the page appear to be correct, but the page contains many items not listed here.

```bash
ubuntu@20160921-rc1:~$ juju model-config
ATTRIBUTE                   FROM     VALUE
agent-metadata-url          default  ""
agent-stream                default  released
agent-version               model    2.0-rc1
apt-ftp-proxy               default  ""
apt-http-proxy              default  ""
apt-https-proxy             default  ""
apt-mirror                  default  ""
automatically-retry-hooks   default  true
default-series              default  xenial
development                 default  false
disable-network-management  default  false
enable-os-refresh-update    default  true
enable-os-upgrade           default  true
firewall-mode               default  instance
ftp-proxy                   default  ""
http-proxy                  default  ""
https-proxy                 default  ""
ignore-machine-addresses    default  false
image-metadata-url          default  ""
image-stream                default  released
logforward-enabled          default  false
logging-config              model    <root>=INFO;unit=DEBUG
no-proxy                    default  ""
provisioner-harvest-mode    default  destroyed
proxy-ssh                   default  false
resource-tags               model    {}
ssl-hostname-verification   default  true
test-mode                   default  false
transmit-vendor-metrics     default  true
```

### CODE REVIEW

**Comment by anastasiamac** [comment]
@matthewhelmke This list looks exhaustive for now. If any new model config settings will be added at a later stage, we'll let you know! Thank you for confirming :D

**Comment by matthewhelmke** [comment]
@anastasiamac Thank you! 

Sorry, follow-up question: as I started editing out the unneeded entries in the page I discovered the following new entries. Can you help me define them with a short sentence or phrase for each?

- ignore-machine-addresses
- logforward-enabled
- transmit-vendor-metrics

**Comment by anastasiamac** [comment]
@matthewhelmke 
From the code comments:
* ignore-machine-addresses: when true, will cause the machine worker not to discover any machine addresses on start up;
* logforward-enabled: determines whether the log forward functionality is enabled;
* transmit-vendor-metrics: determines whether the controller sends metrics collected in this model for anonymized aggregate analytics.

**Comment by matthewhelmke** [comment]
@anastasiamac Thanks again! :)

**Comment by matthewhelmke** [comment]
I also removed outdated entries from the model keys table and added three new ones. The descriptions in that table all read similarly and it might be worth setting aside time in the future to refresh the contents of that table with some readability edits. What do you think, @evilnick ? Shall I create a new issue for that?

**Comment by matthewhelmke** [comment]
Also, @evilnick , this is ready to merge if you are happy with the changes.

**Comment by evilnick** [comment]
Yes. I think particularly the longer explanations need to be taken out of the table and provided below.

but this is good (if accurate!) :+1:

**Pull request merged**
