### PR TITLE
Code fencing howto foo.md

### PR DESCRIPTION
**Pull request by petermatulis**
More code/output fencing on

src/en/howto-*.md

#444 updated

### CODE REVIEW

**Comment by evilnick** [comment]
```
# heading
 
there is a list here:

  - item 1
  - item 2
  - item 3

    ``<backticks>
    some code
    ``<backticks>
  - item 4
```
this is the syntax for fencing code blocks in lists:
indent the backticks as you would any other line of text
leave a blank line if you want a newline for the code

**Comment by petermatulis** [comment]
Was the last comment a FYI only?

All other changes made.

**Comment by evilnick** [comment]
this was just a suggestion, as you said you had difficulty getting them to render properly. This is how they work

**Comment by evilnick** [comment]
@petermatulis I hope that works for you in future

**Pull request merged**
