### PR TITLE
adds prism js for local docs syntax highlighting

### PR DESCRIPTION
**Pull request by evilnick**

### CODE REVIEW

**Comment by evilnick** [comment]
@petermatulis this adds the new syntax highlighting code to local builds. it required a change to the buildtool to rewrite <code> classes in the html.

**Comment by petermatulis** [comment]
tried it; didn't notice a difference to be honest

**Comment by fabricematrat** [comment]
you need to make sure the generate class contains language-yaml for example
The previous syntax higlighter did not support yaml.

**Comment by evilnick** [comment]
It does, that's why I made changes to the build tool. This corks fine for me on pages with code

**Comment by evilnick** [comment]
*works

**Comment by evilnick** [comment]
@petermatulis can we merge this then?

**Comment by petermatulis** [comment]
yeah, let's do it :ok:

**Pull request merged**
