### PR TITLE
Get images from assets server

### PR DESCRIPTION
**Pull request by nottrobin**
Update docs with content from devel

Fixes https://github.com/canonical-webteam/discoursifier/issues/3

### CODE REVIEW

**Comment by pmatulis** [comment]
There's some collateral damage here. I must have neglected to backport to devel something I put into master a few months ago. I will fix post-merge.

Is this file necessary? `src/en/uploaded.json`

**Comment by nottrobin** [comment]
@pmatulis nope, good catch. I'll remove.

**Comment by nottrobin** [comment]
@pmatulis okay it's gone

**Comment by nottrobin** [comment]
@pmatulis also filed https://github.com/juju/docs/pull/3386

**Comment by pmatulis** [comment]
Collateral damage fixed via #3387 (devel backport in #3388)

**Pull request merged**
