### PR TITLE
Fix bad azure credentials documentation.

### PR DESCRIPTION
**Pull request by ExternalReality**
Fixes bug [lp#1690920](https://bugs.launchpad.net/juju/+bug/1690920)

Related Juju PR:
https://github.com/juju/juju/pull/8161

### CODE REVIEW

**Comment by pmatulis** [comment]
Should `tenant-id: <uuid3>` be removed from the commands.md file?

**Comment by ExternalReality** [comment]
@pmatulis It should, and it has.

**Comment by pmatulis** [comment]
Confirm that this is to be backported to all 2.x versions? Not 1.25?

**Comment by ExternalReality** [comment]
@pmatulis I backported to 2.2 because 2.0 is absent `src/en/troubleshooting-clouds.md`. How should I proceed?

**Comment by evilnick** [comment]
If we are backporting to 2.0, we should add that entire file and link to the nav. On the one hand this would be nice, but on the other, 2.0 is out of support now, so I also don't object if we want to skip the effort required for that

**Comment by anastasiamac** [comment]
@evilnick, @pmatulis,
Any chance we can merge this?
If not, please advise on the way forward.

**Comment by pmatulis** [comment]
@ExternalReality I just realized that the changes made to `commands.md` will reappear the next time it's generated (usually we do not edit that file manually) as long as the information remains in `juju help add-credential`. The file is generated from the output to `juju help <command>` using a separate process.
@anastasiamac Can you get the above sorted?

**Comment by pmatulis** [comment]
@ExternalReality I'm updating the troubleshooting.md page and including the troubleshooting-clouds.md page, all from 2.2. Stand by.

**Comment by ExternalReality** [comment]
`src/en/commands.md` has been reverted since it is autogenerated.

**Comment by pmatulis** [comment]
@ExternalReality The 2.0 branch has been updated with the troubleshooting pages from 2.2.

**Comment by ExternalReality** [comment]
@pmatulis The relevant `juju` change has been merged into `juju 2.2`. Are we good to merge this one too?

**Comment by pmatulis** [comment]
@ExternalReality As of now, I do not see why your changes cannot be applied to master. I will then backport to 2.2 and 2.0.

**Comment by evilnick** [comment]
@pmatulis if this is good with you then lets merge

**Comment by ExternalReality** [comment]
$$MERGE$$

**Pull request merged**
