### PR TITLE
added step to enable google compute api - 4a

### PR DESCRIPTION
**Pull request by andrewdmcleod**
as per subject, step to enable google compute api missing from instructions

### CODE REVIEW

**Comment by evilnick** [comment]
Hi, thanks for this.
The gce API was enabled by default on the two projects I created whilst testing this, but I take it this is not always the case?
I will rework step 4 to include a check for this.

**Comment by andrewdmcleod** [comment]
I spun up a stack yesterday and it wasn't enabled by default - maybe its a 'might be needed sometimes' step?

**Comment by evilnick** [comment]
Mine was brand new too, I just opened an account to do the instructions, so it seems there is a lack of consistency. I ran through it twice actually, to check the different with methods, and both projects enabled the API.

I think you are right, a might-be-needed step it is. I will take care of it. And thanks again for pointing this out, I'm sure others would have been tripped up by it.

**Comment by evilnick** [comment]
this was fixed with #445 .
Thanks!

**Pull request closed without merging**
