### PR TITLE
Change urls over to jujucharms.com

### PR DESCRIPTION
**Pull request by huwshimi**
We're about to migrate the juju.ubuntu.com site over to jujucharms.com. As part of that the docs will be at jujucharms.com/docs and so this branch is to update all of the docs links to those new urls.

I have verified the urls with the new site to make sure there are no broken links (there currently is one due to our docs system not updating, it'll be back tomorrow, I am told).

There are two urls that I have not updated due to there being no replacement pages at this point. I have filed bugs for those here:
https://github.com/CanonicalLtd/jujucharms.com/issues/36
https://github.com/CanonicalLtd/jujucharms.com/issues/35

Hope that all makes sense.

### CODE REVIEW

**Comment by huwshimi** [comment]
Oops, apologies for the auto-formatting, not sure what happened there.

**Comment by evilnick** [comment]
Thanks for this. I will check these over in the am - though there are inevitably some links that need to remain hard coded, I want to change as many as possible to relative links anyhow, for various portability reasons.

**Comment by evilnick** [comment]
I will just raise a new pr to convert the ones I want back to relative links.

thanks again!

**Comment by huwshimi** [comment]
No problems, thanks for merging @evilnick!

**Pull request merged**
