### PR TITLE
Developer guide

### PR DESCRIPTION
**Pull request by mbruzek**
This adds a developer guide section above the charm authors section in the 
navigation. This adds the updated content for developers who want to use layers 
and reactive with a focus on the Getting Started Guide and Reference material.

The focus of this PR changes the following:
- Updated Reference guide with Python and Bash examples for Hook Tools
- A Reactive/Layers focus on the charm developer docs
- A guide for implementing Charm Layers
- A guide for implementing Charm interfaces
- An updated Hook Environment variable reference
- Various imports from the existing author docs (thank you contributors)
- Updated charm testing section (incomplete)

Please review the attached guide for organization, correctness, cross-file linking
to the reference guide where applicable.  You will notice that we did not delete any files at this point. The author section is just moved down in the navigation.

### CODE REVIEW

**Comment by evilnick** [comment]
Hello
thanks @mbruzek and @chuckbutler for all your work on this so far.

I think that there are some unresolved issues which are probably best addressed by raising issues against your branch rather than commiting this version to master and breaking stuff that will be hard to unbreak.

I suggest @petermatulis and myself review that branch, raise issues there and we can work through it.

I will leave this open though as it does provide a handy diff of changes

**Comment by marcoceppi** [comment]
Nothing in this pull request removes or deletes anything. We'd appreciate getting this reviewed an in devel docs before 1.26 lands. That said, there are pages we have deprecated, though we have opted not to delete them from the repository yet.

**Comment by mbruzek** [comment]
I merged a contribution from our partners at CloudBase for the powershell equivalent methods!  I love collaboration!

**Comment by jamesbeedy** [comment]
+1

**Comment by petermatulis** [comment]
I'll probably de-merge this today or tomorrow.

**Comment by arosales** [comment]
Peter,

Thanks for the comment and help on the docs. The intent here is to have a development space where folks may collaborate on the new version of the docs. This version is far from a final version and thus is in the development branch. Thus, folks can make small incremental pull requests to the docs and not affect the stable docs. The thought is collaboratively work on getting the -devel docs in shape for Juju 2.0 (April time frame).  I would ask you keep this branch and open an issues or pull requests to get these docs ready for Juju 2.0. We could very much use your expertise in helping shape these docs for Juju 2.0. 

-thanks,
Antonio

**Pull request merged**
