### PR TITLE
Explicitly document positive and negative tags are supported

### PR DESCRIPTION
**Pull request by freyes**
This is a feature supported since juju 2.0

### CODE REVIEW

**Comment by matthewhelmke** [comment]
I can accept this, but before I do, I wonder if it might be helpful to the reader to give a bit more information about what positive and negative tags are. What does this mean?

I'm happy to help massage the manner of expressing the information if I am able to better understand the feature.

**Comment by pmatulis** [comment]
I think: A positive tag identifies a node that has such a tag. A negative tag identifies a node that does *not* have such a tag.

**Comment by freyes** [comment]
@matthewhelmke what peter said, I just borrowed the text from the 'spaces' section.

**Comment by matthewhelmke** [comment]
Ahh, I see that now. I'll approve and merge this and create a new issue for later to expand the definition.

Thank you, @freyes 
:cookie:

**Pull request merged**
