### PR TITLE
Correct an inline link to developers-layers-interfaces

### PR DESCRIPTION
**Pull request by chuckbutler**
correct a 404

### CODE REVIEW

**Comment by pmatulis** [comment]
@chuckbutler Please s/md/html on that link and I'll merge right away. Thanks!

**Comment by chuckbutler** [comment]
Does this still need the s/md/html?

**Comment by evilnick** [comment]
No, I fixed it. And also s/developers/developer
Thats not bad going for you, only two mistakes in a single link ☺

**Comment by chuckbutler** [comment]
I'm glad i have you around to keep my messes to a minimum ;)

**Pull request merged**
