### PR TITLE
Release 2.2-beta4 is the current devel release.

### PR DESCRIPTION
**Pull request by hmlanigan**

### CODE REVIEW

**Comment by mitechie** [comment]
@evilnick I expected the releases file to be gone and the reference-install to be the place now?

**Comment by mitechie** [comment]
@hmlanigan I'm sorry, this releases file is deprecated. Can you make the changes against the reference-install file please?

**Comment by hmlanigan** [comment]
Changes made, @mitechie will add the CentOS beta release info shortly.

**Comment by evilnick** [comment]
@mitechie I thought it was gone as well, didn't you git mv it as part of the getting started thing?
It's not linked anymore anyhow. I will remove it

**Comment by mitechie** [comment]
@evilnick I assumed it didn't make it during the cherry pick somehow.

**Comment by evilnick** [comment]
@mitechie, I thought that may have been the case, but it is still in master. I was positive I saw that moved at some point. Anyhow, I will delete it along with the nav.txt

**Pull request merged**
