### PR TITLE
Fetch multiple versions of the docs into a source tree.

### PR DESCRIPTION
**Pull request by kadams54**

### CODE REVIEW

**Comment by kadams54** [comment]
Take two at doing versioned docs. This script is much smaller and simpler. The idea is to *only* create a source tree with multiple versions of the repo. Since each version is created within a gitignored directory, we sidestep the issues created by checking out different versions within the local repo. Theoretically, the existing build tools (e.g., `build-from-source`) could be modified to generate the final HTML from the generated source tree instead of the original. That is, it would use (perhaps with the help of something like `xargs`) `_versioned_docs/X.Y.Z/source` instead of `source`.

**Comment by kadams54** [comment]
**QA**

1. Run `tools/version.sh`. You should see a usage message.
2. Run `tools/version.sh 1.18.0 master`. You should see messages about fetching each version.
3. Verify that each version is present and accounted for in the `_versioned_src` directory.
4. Run `tools/version.sh -d foobar 1.18.0 master`.
5. Verify that each version is present and accounted for in the `foobar` directory.

**Comment by evilnick** [comment]
cool, i will give that a try. I think this is a more promising route for now, I will start testing!

**Comment by jrwren** [comment]
:+1: QA instructions worked exactly.

**Comment by hatched** [comment]
:+1: Thanks for this!

**Pull request merged**
