### PR TITLE
All links should be relative

### LINKED ISSUE #1313: Broken link
At the bottom of 

https://jujucharms.com/docs/stable/developer-layers

```The Getting started guide contains steps on how to build a layer into a charm.```

has a link to https://jujucharms.com/docs/stable/devel/developer-getting-started#assemble-the-layers , which does not exist.

### PR DESCRIPTION
**Pull request by marcoceppi**
fixes #1313

### CODE REVIEW

**Comment by bac** [comment]
:+1:

**Comment by pmatulis** [comment]
Looks ok but for the future please prepend './' to the links. This is what we have settled on throughout the docs.

**Comment by bac** [comment]
@pmatulis Could someone schedule a review of all docs to make sure we don't have other absolute URLs lurking?

**Comment by pmatulis** [comment]
In master,
```
$ grep -r jujucharms.com * | grep docs

clouds-LXD.md:See [General configuration options](https://jujucharms.com/docs/stable/config-general)
contributing.md:[jujucharms.com](http://jujucharms.com/docs). Its source documents are easy to
howto-drupal-iis.md:Started](https://jujucharms.com/docs/getting-started.html) section to get
howto-node.md:Started](https://jujucharms.com/docs/getting-started.html) section and
reference-release-notes.md:  and Azure. See https://jujucharms.com/docs/devel/storage for more information.
reference-release-notes.md:  documented at https://jujucharms.com/docs/devel/wip-storage.
reference-release-notes.md:  documented at https://jujucharms.com/docs/devel/wip-storage.
reference-release-notes.md:  https://jujucharms.com/docs/1.20/authors-charm-actions
reference-release-notes.md:  https://jujucharms.com/docs/stable/config-vagrant
temp-release-notes.md:https://jujucharms.com/docs/devel/controllers
temp-release-notes.md:    https://jujucharms.com/docs/devel/controllers
temp-release-notes.md:See: https://jujucharms.com/docs/devel/controllers-creating
temp-release-notes.md:See: https://jujucharms.com/docs/devel/clouds
temp-release-notes.md:See: https://jujucharms.com/docs/devel/clouds
temp-release-notes.md:See: https://jujucharms.com/docs/devel/credentials
temp-release-notes.md:https://jujucharms.com/docs/devel/controllers
temp-release-notes.md:https://jujucharms.com/docs/devel/models
temp-release-notes.md:To bootstrap models using the LXD, manual, and MAAS providers, see the special clouds section of: https://jujucharms.com/docs/devel/clouds
temp-release-notes.md:https://jujucharms.com/docs/devel/users
temp-release-notes.md:https://jujucharms.com/docs/devel/users-auth
temp-release-notes.md:https://jujucharms.com/docs/devel/users-creating
temp-release-notes.md:https://jujucharms.com/docs/devel/users-manage
temp-release-notes.md:a bundle of charms. See: https://jujucharms.com/docs/devel/charms-bundles
temp-release-notes.md:GUI charm. See: https://jujucharms.com/docs/devel/controllers-gui
temp-release-notes.md:supporting multiple series. See: https://jujucharms.com/docs/devel/charms-deploying
temp-release-notes.md:The new LXD provider is the best way to use Juju locally. See: https://jujucharms.com/docs/devel/clouds-LXD
temp-release-notes.md:[documentation](https://jujucharms.com/docs/devel/authors-charm-store#entities-explained)

**Comment by bac** [comment]
Thanks for taking a look @pmatulis.  Should we open a new issue to take care of all of those, or just reopen this one?

**Comment by pmatulis** [comment]
Open another issue.

**Comment by pmatulis** [comment]
Backported to 2.0. Closing this.

**Pull request merged**
