### PR TITLE
Hello world example

### PR DESCRIPTION
**Pull request by erik78se**
I've written a tutorial series I hope can help beginners start developing juju charms. I've been whining about this kind of tutorials not existing for a long time and fallen into pretty much all problems existing in the juju development so I figured this would be a contribution.

The last part has not been properly "tested" and I would appreciate if you could give that last part some eyes and I'll happily improve it down the road.

=========== The three parts of this tutorial ==========

PART 1
- Preparing & setup of a basic workbench.
- Creating the example charm with "charm tools".
- Understanding the anatomy of a charm (files and directories).
- Validating & building the charm.
- Adding functionality via a secondary layer (layer:apt).
- Deploying the example charm with juju.

PART 2
- Learn how to add a 'mysql' database interface to charms.
- Write a charm that writes a text-file using a template.
- Deploy the example charm and relate to a mysql charm.
- Use 'juju ssh' to login to the juju unit and display the contents of the text-file.

PART 3
- Make your charm proper to be shared with the community
- Target a specific version (series) of ubuntu for the charm.
- Push a charm to your account in the charmstore
- Deploy your example charm from the charmstore

### CODE REVIEW

**Comment by Ciberth** [comment]
I was busy writing a roadmap myself. Some remarks that I would add:

**Part 1**
- Make a note that the basic layer should always be included!
- Refer to charmsreactive and charmhelpers documentation somewhere 
- First time reactive/layer_example.py code is shown it uses **set_state** -> change this to **set_flag** (I think it' best to not use the term state anymore, or only refer to it as "previously called state" or something)

**Part 2**
- Refer to layer-index!
- a typo: "uploadning" 

**Part 3**
-  Typo: "Im ny case its " <-- love this one ;) 


Further, my roadmap focussed on creating an interface layer. If you are interested we could make it part four (?)

**Comment by pmatulis** [comment]
@erik78se 
@Ciberth 
This is great material that is better destined to become some awesome tutorials hosted on https://tutorials.ubuntu.com/.

Feel free to use this issue to expand, comment, and do anything else you need to do for collaboration purposes.

**Comment by erik78se** [comment]
How can I add to https://tutorials.ubuntu.com/ ?

**Comment by pmatulis** [comment]
That site reads:

*This site is open source and open to contributions from the Linux community, if you have a knack for writing and sharing your knowledge, you can [read our guide](https://tutorials.ubuntu.com/tutorial/tutorial-guidelines) to get started.*

**Comment by evilnick** [comment]
@degville @erik78se  as this is now a tutorial can we close this PR?

**Pull request closed without merging**
