### PR TITLE
Navlinkfix

### LINKED ISSUE #1082: Navigation link broken - juju.html should be juju-managing.html
Navigation link broken - juju.html should be juju-managing.html

Compare with stable.

### PR DESCRIPTION
**Pull request by matthewhelmke**
@juju/docs

Fixes #1082

### CODE REVIEW

**Comment by matthewhelmke** [comment]
WTF? Why are there changes to controllers-ha.md? There are no changes local and I did a git checkout master, git fetch upstream, git merge before modding ONE file. Grr.

**Comment by matthewhelmke** [comment]
However, the changes to controllers-ha.md are necessary... Did we do some sort of rollback in master?? These changes were live from Peter's changes when I looked at our site yesterday.

**Comment by evilnick** [comment]
no, the work peter did didn't change the old commands because we thought it might conflict with the ha work you had done.

**Comment by matthewhelmke** [comment]
Okay, then. We get a 2 for 1 in this PR.

If there are no objections, I'll merge.

**Comment by evilnick** [comment]
not sure what happened there, I'm always suspicious of a long commit list though!
Anyhow :+1:

**Pull request merged**
