### PR TITLE
New charmer policies for Juju 2.0

### PR DESCRIPTION
**Pull request by castrojo**
These are the new ~charmer policies we'd like to implement for Juju 2.0. 

Please see the juju list for discussion. No objections, feedback from the community has been integrated prior to this PR.

### CODE REVIEW

**Comment by evilnick** [comment]
Thanks.

@matthewhelmke this needs turning into English in a few places - should be fairly easy. I suggest you merge it as it is first, then work on revising it. Sound good?

**Comment by matthewhelmke** [comment]
@evilnick Sounds good. I can't do it tonight, but I'll do it Monday at the latest.

**Comment by evilnick** [comment]
oh, I wasn't expecting you to do it in your own time, I was just looking for useful things you could do while I am off :)

**Comment by matthewhelmke** [comment]
:)

**Pull request merged**
