### PR TITLE
Proofread developer guide

### PR DESCRIPTION
**Pull request by AdamIsrael**
This is a work-in-progress review of the updated developer guide. I've tried to keep changes as granular as possible so they can be easily reverted based on feedback. I'll continue adding to this pull request until I've finished my initial review.

### CODE REVIEW

**Comment by chuckbutler** [comment]
+1 I like it.

**Comment by mbruzek** [comment]
Thank you @AdamIsrael for the improvements to the docs.  You also get my +1.

**Comment by evilnick** [comment]
Thanks for this - since (presumably) a lot of things are getting fixed in the new pages, it may help avoid conflicts if you did shorter, faster checks - e.g. a page at a time?

**Comment by petermatulis** [comment]
Yeah, I had already made a PR for debug-dhx but it got lost when the main branch was merged. If you care:

https://github.com/mbruzek/docs/pull/47
https://github.com/mbruzek/docs/pull/46

**Comment by chuckbutler** [comment]
Thats a good point @evilnick 

Its easier to isolate changes and correct incoming conflicts when its only a single page vs several.

**Comment by AdamIsrael** [comment]
Hey @evilnick, that's a good point. Let's consider this a ready-to-review pull request then, and I'll open subsequent ones on a per-page basis.

**Pull request merged**
