### PR TITLE
Changed 'controller' model into 'admin' model

### PR DESCRIPTION
**Pull request by mever**

### CODE REVIEW

**Comment by pmatulis** [comment]
Rejected. The current text is correct. Every controller comes with two models, named 'controller' and 'default'.

**Comment by pmatulis** [comment]
Recall that the master branch follows Juju 2.0.

**Comment by mever** [comment]
On various other places in the documentation it says differently:
https://github.com/juju/docs/blob/master/src/en/models.md#juju-models (third sentence)

Also, when executing "juju list-models" on my machine (juju 2.0-beta7) it says:

> NAME      OWNER        STATUS     LAST CONNECTION
> admin     admin@local  available  never connected
> default*  admin@local  available  44 minutes ago

**Comment by marcoceppi** [comment]
The latest beta, beta9 renames this to controller from admin.

Marco

**Comment by mever** [comment]
Ah, my bad. Thanks for clearing that up for me.

**Pull request closed without merging**
