### PR TITLE
Add page on installing both Juju series

### PR DESCRIPTION
**Pull request by evilnick**
Partially addresses #1487, but more work is needed on other OSes

### CODE REVIEW

**Comment by evilnick** [comment]
@juju/docs @anastasiamac @nskaggs

**Comment by matthewhelmke** [comment]
I think this is a very good start. The info for Ubuntu is clear and easy to follow. Once we are able to get info on other distros and OSes, this page will be even more useful.

**Comment by evilnick** [comment]
I have tacit IRC approval also, so I think we should at least push this to devel

**Comment by matthewhelmke** [comment]
Agreed. We can do new PRs for the other stuff.

**Comment by evilnick** [comment]
though I did just notice some unbalanced parentheses...
i will fix that first :smile:

**Comment by matthewhelmke** [comment]
You would think that I would remember to count parens after that Lisp class in the 1990s...but, no.

**Pull request merged**
