### PR TITLE
Release 1.22.4 is the current proposed release.

### PR DESCRIPTION
**Pull request by sinzui**
We are proposing 1.22.4 to release the older supported 1.22.3. The current Juju is still 1.23.3

### CODE REVIEW

**Comment by marcoceppi** [comment]
This seems weird to say 1.22.4 is the proposed release when 1.23.3  is current. I understand the change but it may be time to grow this page a little more to say what is the latest released version of each minor release of juju we support

**Comment by sinzui** [comment]
We are discussing slowing down releases or moving to LTS releases because customers are demanding fixes to older releases, and rejecting the current supported releases.

**Comment by marcoceppi** [comment]
Sure, this was more a comment on this pages structure, it'd be nice to highlight current releases that are "supported" (?) and what's proposed for those, the next devel/beta/alpha, etc

**Comment by marcoceppi** [comment]
I'll merge this to keep momentum, but just food for thought

**Pull request merged**
