### PR TITLE
Add documentation-builder to 2.2 docs

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
- Fixed a few things in the docs that brakes the documentation encoding to HTML
- Created a navigation metadata.yaml

## QA
- Check out branch 
- Run `documentation-builder --source-folder src --output-media-path 'static/media' --media-url '/static/media' --search-domain 'docs.jujucharms.com' --search-url 'https://docs.ubuntu.com/search' --search-placeholder 'Search Juju docs' --no-link-extensions`
- Open /build/en/ files

### CODE REVIEW

**Comment by pmatulis** [comment]
@anthonydillon OK, no images but I think that's normal at this time? Also, admonishments don't seem to appear when they are preceded by code blocks (see top of charms-destroy.html).

**Comment by anthonydillon** [comment]
@pmatulis thanks, I have fixed the admonishments and the images.

**Comment by pmatulis** [comment]
My web server root is build/en and so I can see files like http://juju.pmatulis.win/juju-concepts.html but I do not get images.

```"GET /media/juju-models.png HTTP/1.1" 500 604 "http://juju.pmatulis.win/juju-concepts"```

**Comment by anthonydillon** [comment]
Ah good point @pmatulis please run this and it should now work:
```
rm -rf build 
documentation-builder --source-folder src --output-media-path 'build/en/static/media' --media-url '/static/media' --tag-manager-code 'GTM-K92JCQ' --search-domain 'docs.jujucharms.com' --search-url 'https://docs.ubuntu.com/search' --search-placeholder 'Search Juju docs' --no-link-extensions
```

**Comment by pmatulis** [comment]
Still troubling.

In, say, about-juju.html, I see:

```charm diagram```

Which **does** allow the image to be displayed.

It's corresponding .md file contains: ```charm diagram```

But in, say, juju-concepts.html, I see:

```machine```

Which does **not** allow the image to be displayed.

It's corresponding .md file contains: ```charm diagram```

So there is a different way of referring to the image in the underlying md files.

I'm looking at why this is the case.

**Comment by pmatulis** [comment]
It looks like it might just be this one file (```juju-concepts.md```). I see one however
(```developer-debug-layers.md```) that shows ```../../media/charm-layers-illustration.png```.

**Comment by pmatulis** [comment]
I believe this is the full list of files that do **not** use ```../media/*.png```:

```
src/en/charms-bundles.md:![Bundle resources in the Charm Store](media/juju2_gui_bundles_store.png)
src/en/charms-bundles.md:![Export button in the Juju GU](media/juju2_gui_bundles_export.png)
src/en/contributing.md:![callout](media/note.png)
src/en/contributing.md:your page use the syntax `![description](media/picture.png)`
src/en/getting-started-keygen-win.md:![](media/puttygen.png)
src/en/help-azure.md:![Juju environment in Azure portal](media/azure_portal-environment.png)
src/en/juju-concepts.md:[img__relations]: ./media/juju-relations.png
src/en/juju-concepts.md:[img__units]: ./media/juju-machine-units.png
src/en/juju-concepts.md:[img__machine-lxd]: ./media/juju-machine-lxd.png
src/en/juju-concepts.md:[img__machine]: ./media/juju-machine.png
src/en/juju-concepts.md:[img__charms]: ./media/juju-charms.png
src/en/juju-concepts.md:[img__models]: ./media/juju-models.png
src/en/juju-concepts.md:[img__client-2]: ./media/juju-client-2.png
src/en/juju-concepts.md:[img__client-3]: ./media/juju-client-3.png
src/en/tut-google.md:![Juju GUI login](media/tut-gce-gui_login280.png)
src/en/tut-google.md:![Juju GUI model switching menu](media/tut-gce-gui_model21.png)
src/en/tut-google.md:![Juju GUI model of MediaWiki bundle](media/tut-gce-gui_mediawiki.png)
src/en/tut-users.md:![Juju GUI model of Canonical Kubernetes](media/tut-users_gui.png)
src/en/tut-users.md:![Juju GUI switching model](media/tut-users_guiswitch.png)
src/en/developer-debug-layers.md:![ charm-layers-illustration.png](../../media/charm-layers-illustration.png)
```

This is the number of references that use the ```../media``` way:

```
git grep png G '\.\./media/' | grep -v debug-layers | wc -l                                                                                                                                                        
61
```

**Comment by pmatulis** [comment]
FYI, a similar thing has happened for HTML links. Many have both `./*.html` and  `../*.html`.

**Comment by anthonydillon** [comment]
@pmatulis Thanks for the feedback. I have updated the image links and changed the documentation-builder arguments a little. I have encapsulated the command into a script so its easier to generate.

Run:
```
./build_docs.sh
```

**Comment by pmatulis** [comment]
- Such change, wow.
 - Re the whitespace changes, did you, by chance, remove any "extraneous" double spaces (2 contiguous spaces) at the end of a line? Sometimes this is deliberate in order to achieve a carriage return.
 - I think you will need to make all these changes again in the 2.3 and devel branches. I presume you used a script.

**Comment by anthonydillon** [comment]
Oh no, I didn't know about the double spacing in markdown files. Damn, I have trim trailing whitespace on save. I will have to turn that off.

I do need to do this again on the `1.25` and `2.3`. Once these and the two other branches land we can land https://github.com/juju/docs/pull/2494

**Comment by anthonydillon** [comment]
After looking into the "extraneous" double spaces it looks like the new Vanilla provides correct padding/space between elements. I don't think we need them.

**Comment by hatched** [comment]
I don't believe that using two hidden characters (most people don't have spaces shown) for layout is a good idea. I believe that you can instead use `\s\s` if a new line is absolutely necessary.

**Comment by anthonydillon** [comment]
@pmatulis I have done all your changes. Please take another look.

**Pull request merged**
