### PR TITLE
Remove media/ directory

### PR DESCRIPTION
**Pull request by nottrobin**
Link to assets.ubuntu.com for all images, and remove the `media/` folder.

Update instructions in `README.md` and `srv/en/contributing.md`.

Now, to add images they should be uploaded at https://manager.assets.ubuntu.com, or to any other image host like https://imgur.com/, and then linked to directly from the Markdown documents.

Fixes https://github.com/ubuntudesign/base-squad/issues/306

QA
--

`./run`, and go to http://localhost:8205, check the site and the images look fine.

### CODE REVIEW

**Comment by pmatulis** [comment]
Once the docs are in Discourse how will (public) user image contributions be reconciled with the assets server? Will there be an automatic process that will convert them over?

**Comment by pmatulis** [comment]
It seems that the README needs more info on how to interact with the assets server.

**Comment by nottrobin** [comment]
@pmatulis once docs are in Discourse, I imagine Discourse users (whether from the community or from Canonical) will upload images through the provided interface:

image

This then gets added to the Markdown like this:

``` markdown
![link-bug|678x500](upload://lAp04qgORzdDFpOVWR26160UL52.png)
```

But is presented as HTML both in Discourse, and will be presented the same in the HTML on the docs website, as:

``` html
<img src="https://discourse.maas.io/uploads/default/optimized/1X/974b19d9fdd4132400764c908cd02f1b285105b4_1_678x500.png" alt="link-bug" width="678" height="500">
```

Of course, you're still free to hand-craft markdown to link to images hosted anywhere, e.g.:

``` markdown
![link-bug](https://assets.ubuntu.com/v1/a23ef56-link-bug.png)

![hot-dog](https://i.imgur.com/g1lFv2e.jpg)
```

Which will also work. And the existing images will remain linked to the assets server.

**Comment by pmatulis** [comment]
@nottrobin What do you mean by "temporary"?

**Comment by nottrobin** [comment]
@pmatulis I mean that this repository will be replaced by Discourse, hopefully before the end of January 2019.

**Comment by pmatulis** [comment]
OK, but my main point remains: In Discourse we'll have images hosted in at least two ways (within Discourse and using the Canonical assets server).

**Comment by nottrobin** [comment]
@pmatulis I answered that here: https://github.com/juju/docs/pull/3207#issuecomment-442455028

We've having 2 discussions here:

1. Instructions for people trying to add images to *this repository*, documented in `README.md` and `contributing.md` - only relevant until January.
2. How people will add images in Discourse

Yes, as [I said](https://github.com/juju/docs/pull/3207#issuecomment-442455028), my plan for number 2 is that existing images will be hosted in the assets server, and then going forward users will (probably) upload them to Discourse and they will be hosted from there. I see no problem at all with this duality.

After the migration to Discourse is complete, if you want to define policies around how images should be hosted and included, or even if you want to go through and replace all assets server images with Discourse hosted ones, or vice versa, you can feel free. But from a technical perspective, there is no problem I can see with images being hosted in both places.

**Comment by pmatulis** [comment]
Understood.

Re dual nature of images,

 1. No one will be patrolling Discourse posts to replace images.
 1. Technically no, but aesthetically and confusingly yes.

**Comment by nottrobin** [comment]
@pmatulis I don't think there's any aesthetic effect at all. The images will display in place in the documentation. Who is going to even notice where they're hosted? I could try to work out how to upload all these images to discouse.jujucharms.com instead of assets.ubuntu.com, but it would just be a lot of work, and personally I don't see at all why it matters.

**Comment by nottrobin** [comment]
@anthonydillon please review?

**Pull request merged**
